version: '3.8'

services:
  mysql-compose:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer-compose:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql-compose
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge